#!/bin/sh
LANG_SHORT=${LANG%%_*}
[ -z "$LANG_SHORT" ] && LANG_SHORT='en'
OPT='/opt/dpkg_get'
BIN='/usr/local/bin'
NEW_CMD="dpkg-get"
NEW_COMMAND=$(printf "%s/%s" $BIN $NEW_CMD)
if [ "$(id -u)" -eq 0 ]; then
    for x in $OPT $BIN; do
        [ ! -d $x ] && mkdir -p $x
    done
    cp -uv dpkg_get.awk $OPT &&
    cp -uv $NEW_CMD $BIN &&
    chmod +x $NEW_COMMAND &&
    case $LANG_SHORT in
        es) printf "\033[1mInstalado correctamente\033[0m\n" ;;
        *) printf "\033[1mSuccessfully installed\033[0m\n" ;;
    esac && exit 0 ||
    case $LANG_SHORT in
        es) printf "\033[2mLa instalación ha fallado\033[0m\n" ;;
        *) printf "\033[2mfailed to install\033[0m\n" ;;
    esac
    exit 1
else
    case $LANG_SHORT in
        es) printf "\033[1;5;38;5;196m¡¡¡Permiso denegado!!!\033[0m\n" ;;
        *) printf "\033[1;5;38;5;196mPermission denied!!!\033[0m\n" ;;
    esac
    exit 100
fi
